// Example region assignments for your data.ts
// Add this `region` property to each state

export type State = {
  name: string;
  territory: boolean;
  population: { count: number };
  region: "West" | "Midwest" | "Northeast" | "South" | "Territory";
};

export const USA_STATES: State[] = [
  { name: "Alabama", territory: false, population: { count: 5108468 }, region: "South" },
  { name: "Alaska", territory: false, population: { count: 733406 }, region: "West" },
  { name: "Arizona", territory: false, population: { count: 7431344 }, region: "West" },
  { name: "Arkansas", territory: false, population: { count: 3067732 }, region: "South" },
  { name: "California", territory: false, population: { count: 38965193 }, region: "West" },
  { name: "Colorado", territory: false, population: { count: 5877610 }, region: "West" },
  { name: "Connecticut", territory: false, population: { count: 3617176 }, region: "Northeast" },
  { name: "Delaware", territory: false, population: { count: 1031890 }, region: "South" },
  { name: "Florida", territory: false, population: { count: 22610726 }, region: "South" },
  { name: "Georgia", territory: false, population: { count: 11029227 }, region: "South" },
  { name: "Hawaii", territory: false, population: { count: 1435138 }, region: "West" },
  { name: "Idaho", territory: false, population: { count: 1964726 }, region: "West" },
  { name: "Illinois", territory: false, population: { count: 12549689 }, region: "Midwest" },
  { name: "Indiana", territory: false, population: { count: 6862199 }, region: "Midwest" },
  { name: "Iowa", territory: false, population: { count: 3207004 }, region: "Midwest" },
  { name: "Kansas", territory: false, population: { count: 2940546 }, region: "Midwest" },
  { name: "Kentucky", territory: false, population: { count: 4526154 }, region: "South" },
  { name: "Louisiana", territory: false, population: { count: 4573749 }, region: "South" },
  { name: "Maine", territory: false, population: { count: 1395722 }, region: "Northeast" },
  { name: "Maryland", territory: false, population: { count: 6180253 }, region: "South" },
  { name: "Massachusetts", territory: false, population: { count: 7001399 }, region: "Northeast" },
  { name: "Michigan", territory: false, population: { count: 10037261 }, region: "Midwest" },
  { name: "Minnesota", territory: false, population: { count: 5737915 }, region: "Midwest" },
  { name: "Mississippi", territory: false, population: { count: 2939690 }, region: "South" },
  { name: "Missouri", territory: false, population: { count: 6196156 }, region: "Midwest" },
  { name: "Montana", territory: false, population: { count: 1132812 }, region: "West" },
  { name: "Nebraska", territory: false, population: { count: 1978379 }, region: "Midwest" },
  { name: "Nevada", territory: false, population: { count: 3194176 }, region: "West" },
  { name: "New Hampshire", territory: false, population: { count: 1402054 }, region: "Northeast" },
  { name: "New Jersey", territory: false, population: { count: 9290841 }, region: "Northeast" },
  { name: "New Mexico", territory: false, population: { count: 2114371 }, region: "West" },
  { name: "New York", territory: false, population: { count: 19571216 }, region: "Northeast" },
  { name: "North Carolina", territory: false, population: { count: 10835491 }, region: "South" },
  { name: "North Dakota", territory: false, population: { count: 783926 }, region: "Midwest" },
  { name: "Ohio", territory: false, population: { count: 11785935 }, region: "Midwest" },
  { name: "Oklahoma", territory: false, population: { count: 4053824 }, region: "South" },
  { name: "Oregon", territory: false, population: { count: 4233358 }, region: "West" },
  { name: "Pennsylvania", territory: false, population: { count: 12961683 }, region: "Northeast" },
  { name: "Rhode Island", territory: false, population: { count: 1095962 }, region: "Northeast" },
  { name: "South Carolina", territory: false, population: { count: 5373555 }, region: "South" },
  { name: "South Dakota", territory: false, population: { count: 919318 }, region: "Midwest" },
  { name: "Tennessee", territory: false, population: { count: 7126489 }, region: "South" },
  { name: "Texas", territory: false, population: { count: 30503301 }, region: "South" },
  { name: "Utah", territory: false, population: { count: 3417734 }, region: "West" },
  { name: "Vermont", territory: false, population: { count: 647464 }, region: "Northeast" },
  { name: "Virginia", territory: false, population: { count: 8715698 }, region: "South" },
  { name: "Washington", territory: false, population: { count: 7812880 }, region: "West" },
  { name: "West Virginia", territory: false, population: { count: 1770071 }, region: "South" },
  { name: "Wisconsin", territory: false, population: { count: 5910955 }, region: "Midwest" },
  { name: "Wyoming", territory: false, population: { count: 584057 }, region: "West" },
  { name: "District of Columbia", territory: true, population: { count: 678972 }, region: "South" },
  { name: "Puerto Rico", territory: true, population: { count: 3194176 }, region: "Territory" },
  { name: "Guam", territory: true, population: { count: 168775 }, region: "Territory" },
  { name: "U.S. Virgin Islands", territory: true, population: { count: 104578 }, region: "Territory" },
  { name: "Northern Mariana Islands", territory: true, population: { count: 55194 }, region: "Territory" },
  { name: "American Samoa", territory: true, population: { count: 55194 }, region: "Territory" },
];
