// data.ts
export type State = {
    name: string;
    territory: boolean;
    population: { count: number };
  };
  
  export const USA_STATES: State[] = [
    { name: "Alabama", territory: false, population: { count: 5108468 } },
    { name: "Alaska", territory: false, population: { count: 733406 } },
    { name: "Arizona", territory: false, population: { count: 7431344 } },
    { name: "Arkansas", territory: false, population: { count: 3067732 } },
    { name: "California", territory: false, population: { count: 38965193 } },
    { name: "Colorado", territory: false, population: { count: 5877610 } },
    { name: "Connecticut", territory: false, population: { count: 3617176 } },
    { name: "Delaware", territory: false, population: { count: 1031890 } },
    { name: "Florida", territory: false, population: { count: 22610726 } },
    { name: "Georgia", territory: false, population: { count: 11029227 } },
    { name: "Hawaii", territory: false, population: { count: 1435138 } },
    { name: "Idaho", territory: false, population: { count: 1964726 } },
    { name: "Illinois", territory: false, population: { count: 12549689 } },
    { name: "Indiana", territory: false, population: { count: 6862199 } },
    { name: "Iowa", territory: false, population: { count: 3207004 } },
    { name: "Kansas", territory: false, population: { count: 2940546 } },
    { name: "Kentucky", territory: false, population: { count: 4526154 } },
    { name: "Louisiana", territory: false, population: { count: 4573749 } },
    { name: "Maine", territory: false, population: { count: 1395722 } },
    { name: "Maryland", territory: false, population: { count: 6180253 } },
    { name: "Massachusetts", territory: false, population: { count: 7001399 } },
    { name: "Michigan", territory: false, population: { count: 10037261 } },
    { name: "Minnesota", territory: false, population: { count: 5737915 } },
    { name: "Mississippi", territory: false, population: { count: 2939690 } },
    { name: "Missouri", territory: false, population: { count: 6196156 } },
    { name: "Montana", territory: false, population: { count: 1132812 } },
    { name: "Nebraska", territory: false, population: { count: 1978379 } },
    { name: "Nevada", territory: false, population: { count: 3194176 } },
    { name: "New Hampshire", territory: false, population: { count: 1402054 } },
    { name: "New Jersey", territory: false, population: { count: 9290841 } },
    { name: "New Mexico", territory: false, population: { count: 2114371 } },
    { name: "New York", territory: false, population: { count: 19571216 } },
    { name: "North Carolina", territory: false, population: { count: 10835491 } },
    { name: "North Dakota", territory: false, population: { count: 783926 } },
    { name: "Ohio", territory: false, population: { count: 11785935 } },
    { name: "Oklahoma", territory: false, population: { count: 4053824 } },
    { name: "Oregon", territory: false, population: { count: 4233358 } },
    { name: "Pennsylvania", territory: false, population: { count: 12961683 } },
    { name: "Rhode Island", territory: false, population: { count: 1095962 } },
    { name: "South Carolina", territory: false, population: { count: 5373555 } },
    { name: "South Dakota", territory: false, population: { count: 919318 } },
    { name: "Tennessee", territory: false, population: { count: 7126489 } },
    { name: "Texas", territory: false, population: { count: 30503301 } },
    { name: "Utah", territory: false, population: { count: 3417734 } },
    { name: "Vermont", territory: false, population: { count: 647464 } },
    { name: "Virginia", territory: false, population: { count: 8715698 } },
    { name: "Washington", territory: false, population: { count: 7812880 } },
    { name: "West Virginia", territory: false, population: { count: 1770071 } },
    { name: "Wisconsin", territory: false, population: { count: 5910955 } },
    { name: "Wyoming", territory: false, population: { count: 584057 } },
    { name: "District of Columbia", territory: true, population: { count: 678972 } },
    { name: "Puerto Rico", territory: true, population: { count: 3194176 } },
    { name: "Guam", territory: true, population: { count: 168775 } },
    { name: "U.S. Virgin Islands", territory: true, population: { count: 104578 } },
    { name: "Northern Mariana Islands", territory: true, population: { count: 55194 } },
    { name: "American Samoa", territory: true, population: { count: 55194 } },
  ];
  